---
version: "3.7"
services:
    minecraft:
        image: pixelmon:1.1
        ports:
            - "25565:25565"
        volumes:    
            - "./pixelmon:/var/srv/pixelmon"
        stdin_open: true
        tty: true
    web:
        image: itzg/rcon
        environment:
            RWA_USERNAME: admin
            RWA_PASSWORD: admin
            RWA_ADMIN: "TRUE"
            # is referring to the hostname of 'mc' compose service below
            RWA_RCON_HOST: minecraft
            # needs to match the password configured for the container, which is 'minecraft' by default
            RWA_RCON_PASSWORD: minecraft
        ports:
            - "4326:4326"
            - "4327:4327"
